plugins {
    id 'java'
    id "io.github.liplum.mgpp" version "1.3.2"
    id 'org.jetbrains.kotlin.jvm'
}

group 'org.example'
version '1.0'
sourceSets {
    main {
        java.srcDirs = ["src"]
    }
}
java {
}
repositories{
    mavenCentral()
    maven{ url "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
    maven{ url 'https://raw.githubusercontent.com/Zelaux/Repo/master/repository' }
    maven{ url 'https://www.jitpack.io' }
}

ext {
    arcLibrary = {String module ->
        return "com.github.Zelaux.ArcLibrary$module:$arcLibraryVersion"
    }
}

dependencies{
    compileOnly "com.github.Anuken.Arc:arc-core:v146"
    compileOnly "com.github.Anuken.Mindustry:core:v146"

    implementation "${arcLibrary(':graphics-draw3d')}"

    annotationProcessor "com.github.Anuken:jabel:93fde537c7"

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    implementation "com.github.plumygames.mktx:core:7a1dc3ff54"
    implementation "com.github.plumygames.mktx:texture:7a1dc3ff54"
    implementation "com.github.plumygames.mktx:dsl:7a1dc3ff54"
    implementation "com.github.liplum.plumyjava:path-kt:1444fba900"
}
mindustry {
    dependency {
        mindustryMirror version: 'v146'
        arc version: 'v146'
    }
    client {
        official version: 'v146'
    }
    server {
        official version: 'v146'
    }
    def name = project.archivesBaseName
    deploy {
        baseName = name
    }
}
mindustryAssets {
    rootAt "$projectDir/assets"
}
kotlin {
    jvmToolchain(8)
}